"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QTCk5tZpHqe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Label} from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export default function userReview(): JSX.Element{
  return (
    <div className="flex flex-col items-center justify-center min-h-[100dvh] bg-gray-100 dark:bg-gray-900 py-12 md:py-16 lg:py-20">
      <div className="container max-w-5xl px-4 md:px-6">
        <div className="grid gap-8 md:grid-cols-[300px_1fr] lg:grid-cols-[400px_1fr] xl:grid-cols-[500px_1fr]">
          <div>
            <img
              alt="Movie Poster"
              className="w-full h-auto rounded-lg shadow-lg"
              height="750"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/750",
                objectFit: "cover",
              }}
              width="500"
            />
          </div>
          <div className="space-y-6">
            <div>
              <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">The Shawshank Redemption</h1>
              <p className="text-gray-500 dark:text-gray-400 mt-2 text-lg">Directed by Frank Darabont</p>
            </div>
            <div className="space-y-4">
              <div>
                <h2 className="text-2xl font-bold">Overview</h2>
                <p className="text-gray-700 dark:text-gray-300 mt-2">
                  Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of
                  common decency.
                </p>
              </div>
              <div>
                <h2 className="text-2xl font-bold">Review</h2>
                <p className="text-gray-700 dark:text-gray-300 mt-2">
                  The Shawshank Redemption is a masterful film that explores the themes of friendship, hope, and the
                  human spirit in the face of adversity. The performances by Tim Robbins and Morgan Freeman are nothing
                  short of exceptional, with their on-screen chemistry and emotional depth captivating the audience from
                  start to finish.
                </p>
                <p className="text-gray-700 dark:text-gray-300 mt-4">
                  The film's pacing is deliberate and thoughtful, allowing the characters and their relationships to
                  develop organically. The attention to detail in the prison setting and the nuanced portrayal of the
                  inmates' daily lives create a sense of authenticity that draws the viewer in.
                </p>
                <p className="text-gray-700 dark:text-gray-300 mt-4">
                  What truly sets The Shawshank Redemption apart, however, is its ability to inspire and uplift. The
                  film's message of perseverance and the triumph of the human spirit in the face of overwhelming odds is
                  both powerful and timeless. It is a testament to the enduring power of cinema to touch the hearts and
                  minds of audiences.
                </p>
              </div>
              <div>
                <h2 className="text-2xl font-bold">Ratings & Accolades</h2>
                <div className="grid grid-cols-2 gap-4 mt-2">
                  <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4">
                    <h3 className="text-lg font-bold">Rotten Tomatoes</h3>
                    <p className="text-gray-700 dark:text-gray-300 mt-2">96% Certified Fresh</p>
                  </div>
                  <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4">
                    <h3 className="text-lg font-bold">IMDB</h3>
                    <p className="text-gray-700 dark:text-gray-300 mt-2">9.3/10 (2.3M reviews)</p>
                  </div>
                  <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4">
                    <h3 className="text-lg font-bold">Metacritic</h3>
                    <p className="text-gray-700 dark:text-gray-300 mt-2">81/100</p>
                  </div>
                  <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4">
                    <h3 className="text-lg font-bold">Awards</h3>
                    <p className="text-gray-700 dark:text-gray-300 mt-2">7 Academy Award nominations, 2 wins</p>
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-2xl font-bold">User Reviews</h2>
                <div className="space-y-4 mt-4">
                  <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8">
                          <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                          <AvatarFallback>JD</AvatarFallback>
                        </Avatar>
                        <div>
                          <h4 className="font-medium">John Doe</h4>
                          <p className="text-gray-500 dark:text-gray-400 text-sm">Reviewed on 2023-06-11</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-1">
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                        <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      </div>
                    </div>
                    <p className="text-gray-700 dark:text-gray-300 mt-4">
                      The Shawshank Redemption is a true masterpiece. The performances, the story, the themes -
                      everything comes together to create a truly unforgettable film. I've watched it multiple times and
                      it never fails to move me. Highly recommended!
                    </p>
                  </div>
                  <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8">
                          <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                          <AvatarFallback>SM</AvatarFallback>
                        </Avatar>
                        <div>
                          <h4 className="font-medium">Sarah Miller</h4>
                          <p className="text-gray-500 dark:text-gray-400 text-sm">Reviewed on 2023-06-10</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-1">
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      </div>
                    </div>
                    <p className="text-gray-700 dark:text-gray-300 mt-4">
                      I absolutely loved this film. The story is so powerful and the performances are incredible. Tim
                      Robbins and Morgan Freeman have such amazing chemistry on screen. It's a must-watch for any movie
                      lover.
                    </p>
                  </div>
                  <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Avatar className="w-8 h-8">
                          <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                          <AvatarFallback>MR</AvatarFallback>
                        </Avatar>
                        <div>
                          <h4 className="font-medium">Michael Rodriguez</h4>
                          <p className="text-gray-500 dark:text-gray-400 text-sm">Reviewed on 2023-06-09</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-1">
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                        <StarIcon className="w-5 h-5 fill-primary" />
                      </div>
                    </div>
                    <p className="text-gray-700 dark:text-gray-300 mt-4">
                      This is one of the best films I've ever seen. The storytelling is so compelling and the characters
                      are so well-developed. I was completely invested in the journey of the two main characters. Truly
                      a cinematic masterpiece.
                    </p>
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-2xl font-bold">Write a Review</h2>
                <form className="space-y-4 mt-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="name">Name</Label>
                      <Input id="name" placeholder="Enter your name" />
                    </div>
                    <div>
                      <Label htmlFor="rating">Rating</Label>
                      <Select defaultValue="5" id="rating">
                        <SelectTrigger>
                          <SelectValue placeholder="Select rating" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="5">5 stars</SelectItem>
                          <SelectItem value="4">4 stars</SelectItem>
                          <SelectItem value="3">3 stars</SelectItem>
                          <SelectItem value="2">2 stars</SelectItem>
                          <SelectItem value="1">1 star</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div>
                    <Label htmlFor="review">Review</Label>
                    <Textarea className="min-h-[150px]" id="review" placeholder="Write your review" />
                  </div>
                  <Button type="submit">Submit Review</Button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

interface IconProps extends React.SVGProps<SVGSVGElement>{}

function StarIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
